name: MacOS Clang

env:
  CMAKE_VERSION: 3.16.x
  CMAKE_BUILD_TYPE: Release
  CMAKE_BUILD_PREFIX: "${{ github.workspace }}/build"
  CMAKE_INSTALL_PREFIX: "${{ github.workspace }}/install"

on:
    push:
    pull_request:

jobs:
  # Checkout apply clang-format and upload artifact
  build:
    name: "Build"
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.0.1

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.10
      with:
        cmake-version: '${{env.CMAKE_VERSION}}'

    - name: Configure
      run: cmake -S ${{ github.workspace }} -B ${{ env.CMAKE_BUILD_PREFIX }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}  -DCMAKE_INSTALL_PREFIX=${{ env.CMAKE_INSTALL_PREFIX }}

    - name: Build
      run: cmake --build ${{ env.CMAKE_BUILD_PREFIX }} --config ${{ env.CMAKE_BUILD_TYPE }} --parallel 2

    - name: Install Strip
      run: cmake --install ${{ env.CMAKE_BUILD_PREFIX }} --config ${{ env.CMAKE_BUILD_TYPE }} --strip

    - name: Run tests
      working-directory: ${{ env.CMAKE_BUILD_PREFIX }}
      run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} -j2 -VV --output-on-failure
