name: Windows M2sys

on:
    push:
    pull_request:
    schedule:
    #Every Sunday at midnight
    - cron:  '0 0 * * 0'

env:
  CMAKE_VERSION: 3.16.x
  NINJA_VERSION: 1.10.2
  BUILD_TYPE: Release
  artifact: "Windows-M2sys.tar.xz"

jobs:

  build:
    name: "Build"
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        path-type: minimal
        release: true
        update: true
        install: git mingw-w64-x86_64-toolchain ccache ninja cmake gcc make llvm python git

    - name: Configure
      working-directory: ${{ github.workspace }}
      run: cmake -S . -G Ninja  -B build -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=../bin

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel 2

    - name: Install Strip
      run: cmake --install build --prefix instdir --strip
      
    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }} -j2 -VV --output-on-failure

  release:
    name: "Release"
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Store Release url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

    - name: Pack
      working-directory: instdir
      run: cmake -E tar cJfv ../${{ env.artifact }} .

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: instdir
        name: ${{ env.artifact }}

  publish:
    if: contains(github.ref, 'tags/v')
    name: "Publish"
    runs-on: ubuntu-latest
    needs: release

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.artifact }}
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v2
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url
    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./${{ env.artifact }}
        asset_name: ${{ env.artifact }}
        asset_content_type: application/x-gtar
